ERROR:root:Vision Machine Broke
Traceback (most recent call last):
  File "GreenVision_NSR.py", line 442, in vision
    log_data(vl_writer)
  File "GreenVision_NSR.py", line 302, in log_data
    image_written])
ValueError: I/O operation on closed file.
ERROR:root:Vision Machine Broke
Traceback (most recent call last):
  File "GreenVision_NSR.py", line 443, in vision
    log_data(vl_writer)
  File "GreenVision_NSR.py", line 303, in log_data
    image_written])
ValueError: I/O operation on closed file.
